Repository 2023-Winter-Bootcamp-Team-N/2023WB-Team-N, pull requests merged in 2024-01, with the labels that each got.

#33 feat: 키워드 검색기능 구현 완료
  backend/account/migrations/0001_initial.py
  backend/account/serializers.py
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#39 fix: search view swagger query parameter 추가
  backend/account/serializers.py
  backend/account/swagger_serializer.py
  backend/account/views.py
Labels: 오류수정

#36 feat: 차트 정보 제공 기능 구현 완료
  backend/account/migrations/0001_initial.py
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#42 [fix] Chart API query parameter 추가
  backend/account/swagger_serializer.py
  backend/account/urls.py
  backend/account/views.py
Labels: 오류수정

#45 [feat] 카테고리 검색 기능
  backend/account/swagger_serializer.py
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#47 [fix] 카테고리별 요약본 목록 불러오기 API 오류 수정
  backend/account/views.py
Labels: 오류수정

#49 [feat] 메인 페이지 퍼블리싱
  frontend/pnpm-lock.yaml
  frontend/src/assets/img/TeamN.svg
  frontend/src/assets/img/animal.svg
  frontend/src/assets/img/art.svg
  frontend/src/assets/img/chart.svg
  frontend/src/assets/img/cook.svg
  frontend/src/assets/img/economy.svg
  frontend/src/assets/img/edu.svg
  frontend/src/assets/img/enter.svg
  frontend/src/assets/img/game.svg
  frontend/src/assets/img/health.svg
  frontend/src/assets/img/music.svg
  frontend/src/assets/img/science.svg
  frontend/src/assets/img/smile.svg
  frontend/src/assets/img/social.svg
  frontend/src/assets/img/sport.svg
  frontend/src/assets/img/stc.svg
  frontend/src/assets/img/travel.svg
  frontend/src/pages/newtab/Chart.js
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.scss
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SearchComponent.css
  frontend/src/pages/newtab/SearchComponent.tsx
Labels: 퍼블리싱

#48 fix: 키워드 검색 기능 수정 완료
  backend/account/serializers.py
  backend/account/urls.py
  backend/account/views.py
Labels: 오류수정

#52 [feat] 요약본 생성 날짜 추가
  backend/account/serializers.py
  backend/account/views.py
Labels: 기능구현

#57 [fix] 작성 날짜 추가 오류 수정
  backend/account/serializers.py
Labels: 오류수정

#54 [feat] 요약본 저장 기능 수정
  backend/account/serializers.py
  backend/account/views.py
Labels: 오류수정

#59 [fix] serializer 오류 수정
  backend/account/views.py
Labels: 오류수정

#63 [feat] URL 추가
  backend/account/migrations/0001_initial.py
  backend/account/models.py
  backend/account/serializers.py
  backend/account/views.py
Labels: 기능구현

#65 [feat] 구독 채널 순위
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#67 [feat] 요약본 중복 방지 기능
  backend/account/views.py
Labels: 기능구현

#69 [feat] 요약본 삭제 기능
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#74 [feat] 요약본 삭제 기능 수정
  backend/account/serializers.py
  backend/account/swagger_serializer.py
  backend/account/urls.py
  backend/account/views.py
Labels: 오류수정

#72 [ feat] 영상 요약 SidePanel 퍼블리싱
  frontend/manifest.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/img/copybutton.svg
  frontend/src/assets/img/mypagebutton.svg
  frontend/src/assets/img/savebutton.svg
  frontend/src/assets/img/teamlogo.svg
  frontend/src/pages/content/index.ts
  frontend/src/pages/content/injected.ts
  frontend/src/pages/content/style.scss
  frontend/src/pages/content/ui/index.tsx
  frontend/src/pages/content/ui/injected.css
  frontend/src/pages/devtools/index.html
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/popup/Popup.tsx
  frontend/src/pages/sidepanel/SidePanel.css
  frontend/src/pages/sidepanel/SidePanel.tsx
  frontend/src/pages/sidepanel/index.css
  frontend/src/shared/storages/exampleThemeStorage.ts
  frontend/tailwind.config.js
  frontend/vite.config.ts
  frontend/webpack.config.js
Labels: 퍼블리싱

#83 [feat] 로그인 기능
  backend/account/urls.py
  backend/account/views.py
Labels: 기능구현

#89 [fix] summary save serializer 수정
  backend/summary/serializers.py
Labels: 오류수정

#96 [fix] setting 수정
  backend/nTeamProject/settings.py
Labels: 오류수정

#99 [fix] settings.py 수정
  backend/nTeamProject/settings.py
Labels: 오류수정

#90 [feat] end_time 삭제
  backend/summary/models.py
  backend/summary/serializers.py
  backend/summary/views.py
Labels: 오류수정

#92 [feat] 요약본 저장 수정
  backend/summary/serializers.py
Labels: 오류수정

#94 [feat] 구독 해지 수정
  backend/account/migrations/0001_initial.py
  backend/subscribe/serializers.py
  backend/subscribe/urls.py
  backend/subscribe/views.py
Labels: 오류수정

#101 [fix] docker compose 오류 수장
  backend/summary/serializers.py
  docker-compose.yml
Labels: 오류수정

#102 [feat] 영상 요약 기능
  backend/nTeamProject/asgi.py
  backend/nTeamProject/settings.py
  backend/requirements.txt
  backend/summary/consumer.py
  backend/summary/routing.py
Labels: 기능구현

#103 [feat] 구독 채널별 요약본
  backend/nTeamProject/settings.py
  backend/summary/urls.py
  backend/summary/views.py
Labels: 기능구현

#105 [refactor] domain 분리 및 오류 수정
  backend/chart/__init__.py
  backend/chart/admin.py
  backend/chart/apps.py
  backend/chart/models.py
  backend/chart/tests.py
  backend/chart/urls.py
  backend/chart/views.py
  backend/nTeamProject/settings.py
  backend/nTeamProject/urls.py
  backend/search/__init__.py
  backend/search/admin.py
  backend/search/apps.py
  backend/search/models.py
  backend/search/tests.py
  backend/search/urls.py
  backend/search/views.py
  backend/summary/urls.py
  backend/summary/views.py
Labels: 리팩토링, 오류수정

#108 [fix] path variable 수정
  backend/search/urls.py
  backend/search/views.py
  backend/summary/serializers.py
Labels: 오류수정

#115 [feat] 채널 이미지 URL 가져오기
  backend/chart/views.py
Labels: 기능구현

#116 [feat] 요약본 저장 임시 수정 완료
  backend/summary/serializers.py
  backend/summary/views.py
Labels: 기능구현

#117 [fix] api key 추가
  backend/chart/views.py
  backend/requirements.txt
  backend/search/views.py
Labels: 기능구현, 기타/세팅

#120 [feat] API 설명 추가
  backend/account/views.py
  backend/chart/views.py
  backend/search/views.py
  backend/subscribe/views.py
  backend/summary/views.py
Labels: 기타/세팅

#122 [feat] CORS setting
  backend/nTeamProject/settings.py
  backend/requirements.txt
Labels: 기타/세팅

#123 [fix] docker-compse.yml 수정
  docker-compose.yml
Labels: 오류수정

#127 [fix] cors setting 수정
  backend/nTeamProject/settings.py
Labels: 기타/세팅, 오류수정

#130 [fix] migrations 오류 수정
  backend/account/migrations/0001_initial.py
  docker-compose.yml
Labels: 오류수정

#107 [feat] 사이드 패널 주소 받아오기
  frontend/manifest.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/img/savedbutton.svg
  frontend/src/assets/img/youtubeimage.jpeg
  frontend/src/assets/style/theme.scss
  frontend/src/pages/background/index.ts
  frontend/src/pages/content/index.ts
  frontend/src/pages/content/ui/app.tsx
  frontend/src/pages/newtab/SummaryPage.css
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현

#137 fix: settings.py 수정
  backend/nTeamProject/settings.py
Labels: 오류수정

#138 [fix] settings.py 수정
  backend/nTeamProject/settings.py
Labels: 오류수정

#139 [fix] migration 오류
  backend/account/migrations/__init__.py
  backend/nTeamProject/settings.py
  backend/subscribe/migrations/0001_initial.py
  backend/subscribe/migrations/__init__.py
  backend/summary/migrations/0001_initial.py
  backend/summary/migrations/__init__.py
Labels: 오류수정

#140 [feat] s3 setting
  backend/nTeamProject/settings.py
  backend/requirements.txt
  backend/summary/s3.py
  backend/summary/views.py
Labels: 기능구현

#142 [docs] swagger api response 최신화
  backend/account/serializers.py
  backend/account/views.py
  backend/chart/serializers.py
  backend/chart/views.py
  backend/search/views.py
  backend/summary/serializers.py
  backend/summary/views.py
Labels: 문서

#143 [fix] 기타 오류 수정
  backend/account/apps.py
  backend/nTeamProject/settings.py
  backend/summary/apps.py
Labels: 오류수정

#145 [feat] 웹 소켓 로직 추가
  backend/summary/consumer.py
Labels: 기능구현, 오류수정

#147 [feat] ssl 임시 설정
  backend/django.crt
  backend/django.key
  backend/nTeamProject/settings.py
  backend/requirements.txt
  docker-compose.yml
Labels: 기능구현, 기타/세팅

#149 [fix] https 해제
  backend/django.crt
  backend/django.key
  backend/nTeamProject/settings.py
  backend/requirements.txt
  docker-compose.yml
Labels: 오류수정

#151 [fix] https, 임시 데이터 생성
  backend/chart/views.py
  backend/django.crt
  backend/django.key
  backend/nTeamProject/settings.py
  backend/requirements.txt
  backend/search/views.py
  backend/test.json
  docker-compose.yml
Labels: 오류수정

#152 [fix] https 해제
  backend/django.crt
  backend/django.key
  backend/nTeamProject/settings.py
  docker-compose.yml
Labels: 오류수정

#156 [feat] 카테고리 별 요약본 검색 API
  backend/account/migrations/0001_initial.py
  backend/search/views.py
  docker-compose.yml
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SummaryItem.ts
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 기능구현

#157 [feat] 모달창에 제목, 채널, 날짜 추가
  backend/account/migrations/0001_initial.py
  frontend/src/pages/newtab/Modal.tsx
Labels: 퍼블리싱

#154 [feat] 요약본 저장 비동기 처리 완료
  .gitignore
  backend/Dockerfile
  backend/nTeamProject/__init__.py
  backend/nTeamProject/celery.py
  backend/nTeamProject/settings.py
  backend/requirements.txt
  backend/summary/apps.py
  backend/summary/s3.py
  backend/summary/tasks.py
  backend/summary/urls.py
  backend/summary/views.py
  docker-compose.yml
Labels: 기능구현

#160 [fix] docker compse 파일 수정
  docker-compose.yml
Labels: 오류수정

#164 [feat] NGINX 연동
  backend/nTeamProject/urls.py
  docker-compose.yml
  init-letsencrypt.sh
  nginx/nginx.conf
Labels: 기능구현, 기타/세팅

#165 [feat] github action test
  .github/workflows/deploy.yml
Labels: 기능구현, 기타/세팅, 테스트

#168 [fix] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: 오류수정

#173 [fix] nginx 80 정상화
  docker-compose.yml
  nginx/nginx.conf
Labels: 오류수정

#175 [feat] test
  docker-compose.yml
  init-letsencrypt.sh
  nginx/nginx.conf
Labels: 테스트

#182 [feat] 차트페이지 퍼블리싱, 구현, 요약본페이지 디자인 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 기능구현

#184 [test] cAdvisor 연동
  backend/summary/cron.py
  docker-compose.yml
  prometheus/config/prometheus.yml
Labels: 테스트

#183 [feat]메인페이지 요약본 전체 조회 가능/ 검색창 기능 완전 구현
  frontend/src/assets/img/All.svg
  frontend/src/assets/img/Convert/edu2.svg
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SummaryItem.ts
  frontend/src/pages/newtab/SummaryPage.css
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 기능구현

#193 [fix] websocket 시간 구별자 전송
  backend/summary/consumer.py
Labels: 오류수정

#191 [fix] 키워드 검색기능에 카테고리 필터링 추가 완료
  backend/nTeamProject/settings.py
  backend/search/views.py
  backend/summary/serializers.py
  elk/docker-compose.elk.yml
  elk/elasticsearch/Dockerfile
  elk/elasticsearch/config/elasticsearch.yml
  elk/filebeat/Dockerfile
  elk/filebeat/config/filebeat.yml
  elk/kibana/Dockerfile
  elk/kibana/config/kibana.yml
  elk/logstash/Dockerfile
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
Labels: 기능구현, 오류수정

#197 [test] github action test
  .github/workflows/cd.yml
  .github/workflows/deploy.yml
Labels: 테스트

#200 [fix] Category Chart 오류수정
  backend/chart/views.py
  backend/summary/urls.py
  backend/summary/views.py
Labels: 오류수정

#203 [test] backend CI test
  .github/workflows/ci.yml
Labels: 테스트

#204 [test CI test
  .github/workflows/ci.yml
  backend/nTeamProject/actions.py
  backend/nTeamProject/settings.py
Labels: 테스트

#211 [feat] logging 추가
  .gitignore
  backend/account/views.py
  backend/chart/views.py
  backend/nTeamProject/settings.py
Labels: 기능구현, 기타/세팅

#213 [fix] docker-compose.prod.yml 수정
  docker-compose.prod.yml
Labels: 오류수정

#214 [feat] SidePanel 요약본 저장 로직 수정
  frontend/manifest.js
  frontend/src/assets/img/categorybutton.svg
  frontend/src/pages/content/index.ts
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/sidepanel/SidePanel.css
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현

#216 [fix] logger 수정
  .gitignore
  backend/account/views.py
  backend/logs/test.log
  docker-compose.prod.yml
  docker-compose.yml
Labels: 오류수정

#217 [feat] 구독채널 퍼블리싱
  frontend/src/assets/fonts/WantedSans-ExtraBold.ttf
  frontend/src/assets/fonts/WantedSansBlack.ttf
  frontend/src/assets/fonts/WantedSansBold.ttf
  frontend/src/assets/fonts/WantedSansExtraBlack.ttf
  frontend/src/assets/fonts/WantedSansMedium.ttf
  frontend/src/assets/fonts/WantedSansSemiBold.ttf
  frontend/src/assets/img/Convert/animal2.svg
  frontend/src/assets/img/Convert/art2.svg
  frontend/src/assets/img/Convert/cook2.svg
  frontend/src/assets/img/Convert/economy2.svg
  frontend/src/assets/img/Convert/edu2.svg
  frontend/src/assets/img/Convert/enter2.svg
  frontend/src/assets/img/Convert/game2.svg
  frontend/src/assets/img/Convert/health2.svg
  frontend/src/assets/img/Convert/music2.svg
  frontend/src/assets/img/Convert/science2.svg
  frontend/src/assets/img/Convert/smile2.svg
  frontend/src/assets/img/Convert/social2.svg
  frontend/src/assets/img/Convert/sport2.svg
  frontend/src/assets/img/Convert/travel2.svg
  frontend/src/assets/img/PieChart.svg
  frontend/src/assets/img/SubscibeText.svg
  frontend/src/assets/img/YoutubeChannelProfile.svg
  frontend/src/assets/img/YoutubeChannelProfile2.svg
  frontend/src/assets/img/YoutubeChannelProfile3.svg
  frontend/src/assets/img/YoutubeChannelProfile4.svg
  frontend/src/assets/img/YoutubeChannelProfile5.svg
  frontend/src/assets/img/YoutubeChannelProfile6.svg
  frontend/src/assets/img/YoutubeChannelProfile7.svg
  frontend/src/assets/img/YoutubeChannelProfile8.svg
  frontend/src/assets/img/barchartTitle.svg
  frontend/src/assets/img/closeButton.svg
  frontend/src/assets/img/leftVector.svg
  frontend/src/assets/img/piechartTitle.svg
  frontend/src/assets/img/previewBlue.svg
  frontend/src/assets/img/rightVector.svg
  frontend/src/assets/img/test1.svg
  frontend/src/assets/img/test2.svg
  frontend/src/assets/img/test3.svg
  frontend/src/assets/img/test4.svg
  frontend/src/assets/img/test5.svg
  frontend/src/assets/img/test6.svg
  frontend/src/assets/img/timeSummaryText.svg
  frontend/src/assets/img/youtubeimage.jpeg
  frontend/src/assets/img/youtubeimage.svg
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribeModal.css
  frontend/src/pages/newtab/SubscribeModal.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/newtab/index.css
  frontend/src/tailwind.css
  frontend/tailwind.config.js
Labels: 퍼블리싱

#222 [feat] 구독 목록 API
  backend/chart/views.py
  backend/nTeamProject/settings.py
  backend/subscribe/serializers.py
  backend/subscribe/urls.py
  backend/subscribe/views.py
Labels: 기능구현, 오류수정

#223 [feat] ELK 연동 성공
  backend/logging/filebeat/filebeat.yml
  backend/logging/logstash/config/logstash.yml
  backend/logging/logstash/pipeline/logstash.conf
  docker-compose.yml
  elk/docker-compose.elk.yml
  elk/elasticsearch/Dockerfile
  elk/elasticsearch/config/elasticsearch.yml
  elk/filebeat/Dockerfile
  elk/filebeat/config/filebeat.yml
  elk/kibana/Dockerfile
  elk/kibana/config/kibana.yml
  elk/logstash/Dockerfile
  elk/logstash/config/logstash.yml
  elk/logstash/pipeline/logstash.conf
Labels: 기타/세팅

#224 [feat] Grafana와 Slack 연동
  prometheus/config/prometheus.yml
Labels: 기능구현

#226 [fix] subscribe models.py 수정
  backend/subscribe/models.py
  docker-compose.yml
Labels: 리팩토링

#230 [fix] swagger 오류 수정
  backend/subscribe/migrations/0001_initial.py
  backend/subscribe/serializers.py
  docker-compose.yml
Labels: 오류수정

#231 [fix] subscribe model 수정 기반으로 코드 리팩토링 완료
  backend/subscribe/migrations/0001_initial.py
  backend/subscribe/serializers.py
  backend/subscribe/urls.py
  backend/subscribe/views.py
Labels: 리팩토링, 오류수정

#232 [fix] subscribe api 수정
  backend/subscribe/migrations/0001_initial.py
  backend/subscribe/serializers.py
  backend/subscribe/views.py
Labels: 기능구현, 리팩토링, 오류수정

#234 [fix] subscribe cancle api 수정 완료
  backend/subscribe/urls.py
  backend/subscribe/views.py
Labels: 오류수정

#235 [fix] subscribe domain swagger 수정
  backend/subscribe/serializers.py
  backend/subscribe/views.py
Labels: 문서

#236 [feat] SidePanel 구독 기능
  frontend/src/assets/img/subscribebutton.svg
  frontend/src/assets/img/subscribedbutton.svg
  frontend/src/pages/newtab/SubscribeModal.tsx
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현

#238 [fix] websocket 오류 수정
  .github/workflows/cd.yml
  backend/requirements.txt
Labels: 오류수정

#239 [fix] test data
  backend/test.json
  docker-compose.yml
Labels: 기타/세팅

#245 [fix] subscribelist api 수정 완료
  backend/subscribe/views.py
Labels: 오류수정

#246 [fix] subscribe api 수정
  backend/subscribe/views.py
  docker-compose.prod.yml
Labels: 기능구현, 오류수정

#243 [rename] versioning 완료
  backend/nTeamProject/urls.py
  docker-compose.yml
Labels: 리팩토링

#247 [fix] docker-compose.prod.yml 수정
  docker-compose.prod.yml
Labels: 기타/세팅

#251 [fix] 모니터링 임시 해제
  docker-compose.prod.yml
Labels: 기타/세팅

#254 [feat] 구독 API 연동 / 메인페이지 전면 수정
  frontend/package-lock.json
  frontend/src/assets/img/All.svg
  frontend/src/assets/img/TeamN.svg
  frontend/src/assets/img/YoutubeChannelProfile.svg
  frontend/src/assets/img/animal.svg
  frontend/src/assets/img/art.svg
  frontend/src/assets/img/chart.svg
  frontend/src/assets/img/cook.svg
  frontend/src/assets/img/economy.svg
  frontend/src/assets/img/edu.svg
  frontend/src/assets/img/enter.svg
  frontend/src/assets/img/game.svg
  frontend/src/assets/img/health.svg
  frontend/src/assets/img/music.svg
  frontend/src/assets/img/previewBlue.svg
  frontend/src/assets/img/science.svg
  frontend/src/assets/img/smile.svg
  frontend/src/assets/img/social.svg
  frontend/src/assets/img/sport.svg
  frontend/src/assets/img/travel.svg
  frontend/src/assets/img/youtubeicon.svg
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribeModal.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현, 퍼블리싱

#256 [feat] 차트페이지, 모달 디자인 수정
  frontend/src/assets/img/InputBar.svg
  frontend/src/assets/img/category.svg
  frontend/src/assets/img/searchIcon.svg
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.css
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 퍼블리싱

#257 [Feat]디자인 전면 수정
  frontend/src/assets/img/All.svg
  frontend/src/assets/img/animal.svg
  frontend/src/assets/img/art.svg
  frontend/src/assets/img/background.svg
  frontend/src/assets/img/category.svg
  frontend/src/assets/img/cook.svg
  frontend/src/assets/img/economy.svg
  frontend/src/assets/img/edu.svg
  frontend/src/assets/img/enter.svg
  frontend/src/assets/img/game.svg
  frontend/src/assets/img/health.svg
  frontend/src/assets/img/music.svg
  frontend/src/assets/img/science.svg
  frontend/src/assets/img/smile.svg
  frontend/src/assets/img/social.svg
  frontend/src/assets/img/sport.svg
  frontend/src/assets/img/travel.svg
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
Labels: 기능구현, 퍼블리싱

#258 [design] 구독 페이지 4*2
  docker-compose.yml
  frontend/src/assets/img/SubscribeText.svg
  frontend/src/assets/img/YoutubeChannelProfile2.svg
  frontend/src/assets/img/YoutubeChannelProfile3.svg
  frontend/src/assets/img/YoutubeChannelProfile4.svg
  frontend/src/assets/img/YoutubeChannelProfile5.svg
  frontend/src/assets/img/YoutubeChannelProfile6.svg
  frontend/src/assets/img/YoutubeChannelProfile7.svg
  frontend/src/assets/img/YoutubeChannelProfile8.svg
  frontend/src/assets/img/YoutubeChannelProfilePlus.svg
  frontend/src/assets/img/channelBg.svg
  frontend/src/assets/img/channelBox.svg
  frontend/src/assets/img/lastyoutubeimage.png
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
Labels: 퍼블리싱

#259 [feat]메인페이지 디자인 전면 수정 완료
  frontend/src/assets/img/TeamN.svg
  frontend/src/assets/img/background.svg
  frontend/src/assets/img/bluebackground.svg
  frontend/src/assets/img/chart.svg
  frontend/src/assets/img/main_background.svg
  frontend/src/assets/img/youtubeicon.svg
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SummaryPage.css
Labels: 퍼블리싱

#260 [design] 구독 페이지 디자인 수정
  frontend/src/assets/img/SubscribeText.svg
  frontend/src/assets/img/channelBg.svg
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 퍼블리싱

#261 [feat] 디자인 전면 수정
  frontend/src/assets/img/barchartTitle.svg
  frontend/src/assets/img/leftVector.svg
  frontend/src/assets/img/piechartTitle.svg
  frontend/src/assets/img/rightVector.svg
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 퍼블리싱

#263 [design] SidePanel 스타일 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/img/logo.svg
  frontend/src/assets/img/transparencylogo.svg
  frontend/src/pages/newtab/index.html
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 스타일

#265 [fix]구독채널 로고 선택 시 이동하도록 수정
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
Labels: 퍼블리싱

#267 [feat] 로고 위치 수정
  frontend/src/assets/img/logo.svg
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
Labels: 퍼블리싱

#269 [feat] 모달창, 서머리페이지, 차트페이지 디자인 수정
  frontend/src/assets/img/barchartTitle.svg
  frontend/src/assets/img/piechartTitle.svg
  frontend/src/assets/img/timeSummaryText.svg
  frontend/src/pages/newtab/ChartComponent.tsx
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Modal.tsx
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SummaryPage.css
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 퍼블리싱

#271 [fix] 디자인 수정 / 채널 선택 후 페이지 이동시 요약창 닫힘
  frontend/src/assets/img/All.svg
  frontend/src/assets/img/animal.svg
  frontend/src/assets/img/art.svg
  frontend/src/assets/img/chart.svg
  frontend/src/assets/img/cook.svg
  frontend/src/assets/img/economy.svg
  frontend/src/assets/img/edu.svg
  frontend/src/assets/img/enter.svg
  frontend/src/assets/img/game.svg
  frontend/src/assets/img/health.svg
  frontend/src/assets/img/music.svg
  frontend/src/assets/img/science.svg
  frontend/src/assets/img/smile.svg
  frontend/src/assets/img/social.svg
  frontend/src/assets/img/sport.svg
  frontend/src/assets/img/travel.svg
  frontend/src/assets/img/youtubeicon.svg
  frontend/src/pages/newtab/Newtab.css
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.tsx
Labels: 퍼블리싱

#274 [feat] 버튼위치 변경
  frontend/src/pages/newtab/ChartComponent2.tsx
  frontend/src/pages/newtab/Newtab.tsx
Labels: 스타일

#278 [feat]스켈레톤 UI / 모든 오류 수정
  frontend/src/assets/img/dropdownButton.svg
  frontend/src/assets/img/dropdownButtonDark.svg
  frontend/src/pages/newtab/Newtab.tsx
  frontend/src/pages/newtab/SubscribePage.css
  frontend/src/pages/newtab/SubscribePage.tsx
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/sidepanel/Dropdown.css
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 기능구현, 퍼블리싱

#280 [feat] 구독 삭제 버튼 재구현 및 디자인 수정
  frontend/src/pages/newtab/SummaryPage.tsx
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 퍼블리싱

#282 [feat] 드롭다운 알러트(모달창) 구현
  frontend/src/pages/sidepanel/Modal.css
  frontend/src/pages/sidepanel/SidePanel.tsx
Labels: 퍼블리싱

#284 [feat] 서머리 페이지 호버효과 수정
  frontend/src/pages/newtab/SummaryPage.tsx
Labels: 퍼블리싱

#283 [fix] 요약본 중복 저장 수정
  backend/summary/views.py
  docker-compose.yml
Labels: 오류수정

#287 [fix] chart api 수정
  backend/chart/views.py
  docker-compose.yml
Labels: 오류수정
